<?php
/**
 * THIS FILE IS AUTO-GENERATED BY LAZYRECORD,
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY.
 * 
 * Last Modified: October 12th at 11:04pm
 */
namespace LazyRecord\Model;


use LazyRecord;
use LazyRecord\Schema\RuntimeSchema;
use LazyRecord\Schema\Relationship;

class MetadataSchemaProxy extends RuntimeSchema
{

    public static $column_names = array (
  0 => 'id',
  1 => 'name',
  2 => 'value',
);
    public static $column_hash = array (
  'id' => 1,
  'name' => 1,
  'value' => 1,
);
    public static $mixin_classes = array (
);
    public static $column_names_include_virtual = array (
  0 => 'id',
  1 => 'name',
  2 => 'value',
);

    const schema_class = 'LazyRecord\\Model\\MetadataSchema';
    const collection_class = 'LazyRecord\\Model\\MetadataCollection';
    const model_class = 'LazyRecord\\Model\\Metadata';
    const model_name = 'Metadata';
    const model_namespace = 'LazyRecord\\Model';
    const primary_key = 'id';
    const table = '__meta__';
    const label = 'Metadata';

    public function __construct()
    {
        /** columns might have closure, so it can not be const */
        $this->columnData      = array( 
  'id' => array( 
      'name' => 'id',
      'attributes' => array( 
          'locales' => NULL,
          'attributes' => array( 
              'autoIncrement' => true,
            ),
          'name' => 'id',
          'primary' => true,
          'unsigned' => NULL,
          'type' => 'int',
          'isa' => 'int',
          'notNull' => NULL,
          'enum' => NULL,
          'set' => NULL,
          'autoIncrement' => true,
        ),
    ),
  'name' => array( 
      'name' => 'name',
      'attributes' => array( 
          'locales' => NULL,
          'attributes' => array( 
              'length' => 128,
            ),
          'name' => 'name',
          'primary' => NULL,
          'unsigned' => NULL,
          'type' => 'varchar',
          'isa' => 'str',
          'notNull' => NULL,
          'enum' => NULL,
          'set' => NULL,
          'length' => 128,
        ),
    ),
  'value' => array( 
      'name' => 'value',
      'attributes' => array( 
          'locales' => NULL,
          'attributes' => array( 
              'length' => 256,
            ),
          'name' => 'value',
          'primary' => NULL,
          'unsigned' => NULL,
          'type' => 'varchar',
          'isa' => 'str',
          'notNull' => NULL,
          'enum' => NULL,
          'set' => NULL,
          'length' => 256,
        ),
    ),
);
        $this->columnNames     = array( 
  'id',
  'name',
  'value',
);
        $this->primaryKey      = 'id';
        $this->table           = '__meta__';
        $this->modelClass      = 'LazyRecord\\Model\\Metadata';
        $this->collectionClass = 'LazyRecord\\Model\\MetadataCollection';
        $this->label           = 'Metadata';
        $this->relations       = array( 
);
        $this->readSourceId    = 'default';
        $this->writeSourceId    = 'default';
        parent::__construct();
    }


    /**
     * Code block for message id parser.
     */
    private function __() {
        _('Metadata');
    }

}
