#!/bin/bash
set -e
cd examples/todos
php ../../bin/maghead use db/config/database.yml
php ../../bin/maghead schema build -f
php ../../bin/maghead db create master
# add testing2 database to the server
php ../../bin/maghead sql --rebuild --basedata
