#!/bin/bash
# echo $TRAVIS_PHP_VERSION
# phpenv config-rm xdebug.ini
if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then
    echo 'date.timezone = "Asia/Taipei"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    # the below two seems don't work
    phpenv config-add travis/php.ini
    phpenv config-add travis/php-exts.ini


    git clone https://github.com/krakjoe/pthreads
    (cd pthreads && phpize && ./configure && make install)

    # install pthreads.so
    echo "extension = pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
fi
