#!/bin/bash
# echo $TRAVIS_PHP_VERSION
# phpenv config-rm xdebug.ini

if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then
    echo 'date.timezone = "Asia/Taipei"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    # the below two seems don't work
    phpenv config-add travis/php.ini
    phpenv config-add travis/php-exts.ini

    mkdir exts
    if [[ -e exts/pthreads ]] ; then
        (cd exts/pthreads && git pull)
    else
        git clone https://github.com/krakjoe/pthreads exts/pthreads
    fi

    ./travis/setup-php-exts

    echo "extension = pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    echo "extension = gearman.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

    # echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    # echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    # echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
fi
